name: Satellite Notifier

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # This step checks out the repository to the runner, allowing the workflow to access the code.

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        # This step sets up the Python environment with the specified version.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        # This step upgrades pip and installs the necessary dependencies for the script.

      - name: Run script
        env:
          SATELLITE_API_KEY: ${{ secrets.SATELLITE_API_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          ALTITUDE: ${{ secrets.ALTITUDE }}
          SATELLITE_ID: ${{ secrets.SATELLITE_ID }}
        run: python main.py
        # This step runs the Python script with the environment variables needed for the satellite notification process.