name: Satellite Notifier

on:
  schedule:
    - cron: '0 0-12 * * 6,0'  # Runs the workflow between 19:00 and 07:00 in UTC-5 on Saturday (6) and Sunday (0)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pytz
          pip install pandas

      - name: Run script
        env:
          SATELLITE_API_KEY: ${{ secrets.SATELLITE_API_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          ALTITUDE: ${{ secrets.ALTITUDE }}
          SATELLITE_ID: ${{ secrets.SATELLITE_ID }}
          LOG_DIRECTORY: ${{ secrets.LOG_DIRECTORY }}
          LOG_FILE: ${{ secrets.LOG_FILE }}  
        run: python main.py

      - name: Auto commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Change
          commit_user_name: My GitHub Actions Bot
          commit_user_email: ${{ secrets.EMAIL_USER }}
          commit_author: 'Jorge Cardona <${{ secrets.EMAIL_USER }}>'
